### ISSUE TITLE
Sign Up- Invalid Credentials (v0.1_Test_Case_No.= HEXABYTES 2 )

### ISSUE THREAD

**Issue by shubhamagain7** [Sayantan03/HEXABYTES#1]
Sign up successful with invalid Name format.
[Name cannot have numeric value]

Signup successful with invalid email.
[email should end with .com/.in not like .12/.55]

**Comment by siddhartha1997** [comment]
Invalid Name Format is solved by matching the input text with "^[A-Za-z\s]{1,}[\.]{0,1}[A-Za-z\s]{0,}$" regular expression in <input> tag of HTML.

Invalid Email is solved by matching the input text with "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,3}$" regular expression in <input> tag of HTML.

**Comment by shubhamagain7** [comment]
Fix Verified.
