### ISSUE TITLE
 Make Payment- Valid Credentials (v0.1_Test_Case_No. = HEXABYTES-12,13)

### ISSUE THREAD

**Issue by shubhamagain7** [Sayantan03/HEXABYTES#4]
Accepting wrong format of Card card details

Date in card will be (dd/mm) format not  (dd/mm/yyyy).

**Comment by siddhartha1997** [comment]
input type field is changed from date to month. 
Earlier version: 
input type="date"
New Modified Version:
input type="month"

**Comment by shubhamagain7** [comment]
Fix Verified
