### ISSUE TITLE
Booking Unreserved Ticket (v0.2_Test_Case_No. = HEXABYTES-1) 

### ISSUE THREAD

**Issue by shubhamagain7** [Sayantan03/HEXABYTES#5]
1) Number of Passenger per ticket, should have a limit.

2) System should not accept Decimal value in number of passenger

Do some validation

**Comment by subham812** [comment]
1. Validated in JavaScript by adding a condition
if(nop>6) //where "nop" is number of passenger taken from user
{
alert("Maximum limit is 6");
document.getElementById("inpfrm").reset();//where "inpfrm" is the identity of the form
}

2. Validated in JavaScript by checking whether the number in whole number or not
var result = (nop - Math.floor(nop)) !== 0; //where "nop" is number of passenger taken from user
if (result)
{
alert("Passenger count should be in whole number");
document.getElementById("inpfrm").reset(); //where "inpfrm" is the identity of the form
}

**Comment by shubhamagain7** [comment]
Bugs Fixed.
