### ISSUE TITLE
Book special Pass (v0.2_Test_Case_No. = HEXABYTES-9) 

### ISSUE THREAD

**Issue by shubhamagain7** [Sayantan03/HEXABYTES#6]
No tram service in midnight (10.00 PM to 08.00 AM)

System accepting this above mention time duration in Booking Start Time and Booking End Time.

Inconsistency to be removed.

**Comment by subham812** [comment]
- Night time is checked by the following in JavaScript
var diff = et - st; // Where "et" stands for end time and "st" stands for start time
if(diff<0)
{
alert("Night Shifts are not applicable");
document.getElementById("spclbk").reset();
}

- Time Window is checked by the following validation in JavaScript
if(st<800 || et>2200) // Where "et" stands for end time and "st" stands for start time
{
alert("Tram services are available from 8AM to 10PM");
document.getElementById("spclbk").reset();
}

**Comment by shubhamagain7** [comment]
Bugs Fixed.
